apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: r-mlops-k8s-9-1-3-22209764
  annotations:
    serving.kserve.io/s3-endpoint: https://storage.yandexcloud.net
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: ru-central1
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: YCAJEM0FLQT54ub8YXrWVjek5
  AWS_SECRET_ACCESS_KEY: YCP3qXdShHOaJX6gN2OzA0NPM1IbPheIuVrAHcYi