apiVersion: v1
kind: Secret # тип сервиса
metadata:
  name: s3-secret-nil # Имя секрета; по нему секрет подключается к ServiceAccount и подхватывается storage‑initializer.
  namespace: r-mlops-k8s-9-1-3-22209764 # Namespace секрета; должен совпадать с namespace InferenceService и ServiceAccount.
  annotations:
    serving.kserve.io/s3-endpoint: storage.yandexcloud.net:443 # Классический адрес для YC
    serving.kserve.io/s3-usehttps: "1" # Включает HTTPS при обращении к endpoint
    serving.kserve.io/s3-verifyssl: "1" # Требовать проверку TLS‑сертификата
    serving.kserve.io/s3-region: "ru-central1"
type: Opaque # Тип секрета «произвольные данные» (generic), подходит для пары ключ/значение.
stringData:
  AWS_ACCESS_KEY_ID: "" 
  AWS_SECRET_ACCESS_KEY: "" 